//DELETE  http://localhost:3001/api/persons/69425d1ec24052046db92dd2
//GET  http://localhost:3001/api/notes/

POST   http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "aa",
  "number": "02-2477296"
}